"""Shared fixtures for tool conformance tests.

Generates minimal valid samples of each binary format the tools claim
to support (txt, csv, xlsx, docx, pdf, png), backed by a session-scoped
tmp dir so we only build them once per pytest run. Each fixture has a
known sentinel string embedded so tests can assert the tool actually
extracted content rather than returning empty.

We deliberately avoid heavyweight optional deps (reportlab,
python-docx) — the fixtures are hand-rolled with stdlib + openpyxl +
PIL, all of which are already installed.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

import pytest


# Sentinel strings — short, unique, easy to grep for in extracted output.
TXT_SENTINEL = "SENTINEL_TXT_TOOL_CONFORMANCE"
CSV_SENTINEL = "SENTINEL_CSV_TOOL_CONFORMANCE"
XLSX_SENTINEL = "SENTINEL_XLSX_TOOL_CONFORMANCE"
DOCX_SENTINEL = "SENTINEL_DOCX_TOOL_CONFORMANCE"
PDF_SENTINEL = "SENTINEL_PDF_TOOL_CONFORMANCE"


# ---------------------------------------------------------------------------
# Format builders
# ---------------------------------------------------------------------------

def _build_txt(path: Path) -> None:
    path.write_text(
        f"line 1\n"
        f"{TXT_SENTINEL}\n"
        f"line 3 with some extra content\n",
        encoding="utf-8",
    )


def _build_csv(path: Path) -> None:
    path.write_text(
        "name,value,note\n"
        f"alice,42,{CSV_SENTINEL}\n"
        "bob,17,plain\n"
        "carol,3.14,decimal\n",
        encoding="utf-8",
    )


def _build_xlsx(path: Path) -> None:
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Summary"
    ws["A1"] = "name"
    ws["B1"] = "value"
    ws["A2"] = "alice"
    ws["B2"] = 42
    ws["A3"] = "bob"
    ws["B3"] = XLSX_SENTINEL
    ws2 = wb.create_sheet("Detail")
    ws2["A1"] = "key"
    ws2["B1"] = "v"
    ws2["A2"] = "k1"
    ws2["B2"] = 100
    wb.save(path)


def _build_docx(path: Path) -> None:
    """Hand-roll a minimal .docx (it's a zip with a few XMLs)."""
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '</Types>'
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
        '</Relationships>'
    )
    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:body>'
        f'<w:p><w:r><w:t>{DOCX_SENTINEL}</w:t></w:r></w:p>'
        '<w:p><w:r><w:t>Fred drew Michael in Secret Santa.</w:t></w:r></w:p>'
        '</w:body>'
        '</w:document>'
    )
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("word/document.xml", document)


def _build_pdf(path: Path) -> None:
    """Hand-rolled minimal one-page PDF with our sentinel text.

    We avoid a reportlab dep — the PDF structure is small enough to
    write directly. Generated bytes parse cleanly with pypdf 6.x.
    """
    text_stream = (
        b"BT /F1 18 Tf 50 700 Td ("
        + PDF_SENTINEL.encode("ascii")
        + b") Tj ET"
    )
    # Build the object table; track byte offsets for xref.
    parts: list[bytes] = []
    offsets: list[int] = [0]  # 0th entry is the free entry in xref

    def add(obj: bytes) -> None:
        offsets.append(sum(len(p) for p in parts))
        parts.append(obj)

    parts.append(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")  # binary-marker comment
    add(b"1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendobj\n")
    add(b"2 0 obj\n<</Type/Pages/Kids[3 0 R]/Count 1>>\nendobj\n")
    add(
        b"3 0 obj\n<</Type/Page/Parent 2 0 R"
        b"/Resources<</Font<</F1 4 0 R>>>>"
        b"/MediaBox[0 0 612 792]/Contents 5 0 R>>\nendobj\n"
    )
    add(b"4 0 obj\n<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>\nendobj\n")
    add(
        b"5 0 obj\n<</Length "
        + str(len(text_stream)).encode("ascii")
        + b">>\nstream\n"
        + text_stream
        + b"\nendstream\nendobj\n"
    )
    body = b"".join(parts)
    xref_off = len(body)
    xref_lines = [b"xref\n0 6\n", b"0000000000 65535 f \n"]
    # Offsets for objects 1..5 — each must be a 10-digit decimal.
    for off in offsets[1:]:
        xref_lines.append(f"{off:010d} 00000 n \n".encode("ascii"))
    trailer = (
        b"trailer\n<</Size 6/Root 1 0 R>>\nstartxref\n"
        + str(xref_off).encode("ascii")
        + b"\n%%EOF\n"
    )
    path.write_bytes(body + b"".join(xref_lines) + trailer)


def _build_png(path: Path) -> None:
    from PIL import Image
    img = Image.new("RGB", (32, 32), color=(255, 0, 0))
    img.save(path, "PNG")


# ---------------------------------------------------------------------------
# Session fixture: builds everything once.
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def fixtures_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    d = tmp_path_factory.mktemp("tool_conformance_fixtures")
    _build_txt(d / "sample.txt")
    _build_csv(d / "sample.csv")
    _build_xlsx(d / "sample.xlsx")
    _build_docx(d / "sample.docx")
    _build_pdf(d / "sample.pdf")
    _build_png(d / "sample.png")
    return d


@pytest.fixture(scope="session")
def fixture_paths(fixtures_dir: Path) -> dict[str, Path]:
    return {
        "txt": fixtures_dir / "sample.txt",
        "csv": fixtures_dir / "sample.csv",
        "xlsx": fixtures_dir / "sample.xlsx",
        "docx": fixtures_dir / "sample.docx",
        "pdf": fixtures_dir / "sample.pdf",
        "png": fixtures_dir / "sample.png",
    }


# Re-export sentinel strings so tests can import them by name.
SENTINELS = {
    "txt": TXT_SENTINEL,
    "csv": CSV_SENTINEL,
    "xlsx": XLSX_SENTINEL,
    "docx": DOCX_SENTINEL,
    "pdf": PDF_SENTINEL,
}
