services:
  yacy:
    image: yacy/yacy_search_server:latest
    container_name: yacy_search_server
    ports:
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:8443:8443"
    volumes:
      - yacy_search_server_data:/opt/yacy_search_server/DATA
    restart: unless-stopped
    logging:
      options:
        max-size: "200m"
        max-file: "2"

volumes:
  yacy_search_server_data:
